language: go
go:
- 1.x
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/mitchellh/gox
script:
- "$HOME/gopath/bin/goveralls -service=travis-ci -v"
- gox -output "bin/{{.Dir}}_{{.OS}}_{{.Arch}}" -osarch "darwin/amd64 linux/amd64 linux/arm windows/amd64" ./...
deploy:
  provider: releases
  api_key:
    secure: "ISBkRDquOVqmhZ75hk5RAcPtL6FFGZGB3sIzxR8HZuG82GMvDcq2rt90LsxNN986MTsVXT9+RwwODGGVmZad8Fvupg+EFPMGHcaiMjKxGCDyUwzHpsDYMPGEzczlhKmgDbEM02cOinFDFhHVs10e2rGz4nLQVo3TGxmjkEK1tvlX/+yevtsisEAodwrByRXVD+/kFgx7hle7HtVQW+mMmzMMYs8Z53R8+7v1qTzRZJ2MvmOfuQ4Q3KPvHVKW9WPoAmFGccSD30QHk4XAH1g87vQK1rg8oJS+dqVkgfB3dptMpiVqoBEqJIahITi85QHNiksyTka4/RAtVYULEfYMr+nsVX68P7pW/K8K0qeC8Q6Nlhw45E1If7zPcLy42E55XZTRCCcjHdKhbKBSgyeD0eE3GjbBe0U62skidCWmu2v3aJG3Ts48eRLhmJ6LonfeFdr8cV/f5n5xj/X0uSW+R8FnktHBjswv4nvEasx589/QX0bmSJafARIRZ1Uh7u/tgJuD3ZXQ43EMnuDf7Juw+MkuKmHg331mTkS4Y2HzFQt9K3t7HrGOvPHvKXNbSx6EAn3OWrBlI7OgSZEVrOGNqszSlWz/D2q/4t/2HClnc+5dha2EIdePledjqBk1FYmRwxOkMiV1HyiPwWF8bCdY07ZWK+/mgOK8uH3wdCHahN4="
  file:
  - bin/kazaam_darwin_amd64
  - bin/kazaam_linux_amd64
  - bin/kazaam_linux_arm
  - bin/kazaam_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: true
env:
  global:
